# Generated by Django 3.0.5 on 2020-05-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200512_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_code',
            field=models.CharField(default='5132020619461', max_length=30, verbose_name='User code'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_code',
            field=models.CharField(blank=True, default='team135617568', max_length=20, unique=True, verbose_name='Code'),
        ),
    ]
