# Generated by Django 3.0.5 on 2020-05-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200513_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_code',
            field=models.CharField(default='5142020183920', max_length=30, verbose_name='User code'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_code',
            field=models.CharField(blank=True, default='team145181444', max_length=20, unique=True, verbose_name='Code'),
        ),
    ]
