from . import views
from django.urls import path , include
from django.contrib.admin.views.decorators import staff_member_required
from tickets import views as ticket_views 

urlpatterns = [
    path('', ticket_views.dashboard, name='ticket-dashboard'),
    path('ticket/<int:pk>/', ticket_views.ticket_detail, name='ticket-detail'),
    #path('ticket/list/<str:type>/<str:value>/', staff_member_required(ticket_views.FilteredTicketListView.as_view()), name='ticket-filtered-list'),
    path('ticket/list/', ticket_views.ticket_list, name='ticket-list'),
    path('ticket/<int:pk>/update/', ticket_views.ticket_update, name='ticket-update'),
    path('ticket/<int:pk>/delete/', staff_member_required(ticket_views.TicketDeleteView.as_view()), name='ticket-delete'),
    path('ticket/new/', ticket_views.create_ticket, name='ticket-create'),
    path('category/new/', staff_member_required(ticket_views.CategoryCreateView.as_view()), name='category-create'),
    path('category/list/', ticket_views.category_list, name='category-list'),
    path('category/<int:pk>/delete/', staff_member_required(ticket_views.CategoryDeleteView.as_view()), name='category-delete'),
    path('category/<int:pk>/update/', ticket_views.CategoryUpdateView.as_view(), name='category-update'),
    path('category/<int:pk>/', staff_member_required(ticket_views.CategoryDetailView.as_view()), name='category-detail'),
    path('subcategory/new/', staff_member_required(ticket_views.SubCategoryCreateView.as_view()), name='subcategory-create'),
    path('subcategory/list/', ticket_views.subcategory_list, name='subcategory-list'),
    path('subcategory/<int:pk>/delete/', staff_member_required(ticket_views.SubCategoryDeleteView.as_view()), name='subcategory-delete'),
    path('subcategory/<int:pk>/update/', ticket_views.SubCategoryUpdateView.as_view(), name='subcategory-update'),
    path('subcategory/<int:pk>/', staff_member_required(ticket_views.SubCategoryDetailView.as_view()), name='subcategory-detail'),
    path('project/new/', ticket_views.create_project, name='project-create'),
    path('project/list/', ticket_views.project_list, name='project-list'),
    path('project/<int:pk>/', staff_member_required(ticket_views.ProjectDetailView.as_view()), name='project-detail'),
    path('project/update/<int:pk>/', ticket_views.update_project, name='project-update'),
    path('project/delete/<int:pk>/', staff_member_required(ticket_views.ProjectDeleteView.as_view()), name='project-delete'),
    path('product/new/', ticket_views.create_product, name='product-create'),
    path('product/list/', ticket_views.product_list, name='product-list'),
    path('product/<int:pk>/delete/', staff_member_required(ticket_views.ProductDeleteView.as_view()), name='product-delete'),
    path('product/<int:pk>/update/', ticket_views.ProductUpdateView.as_view(), name='product-update'),
    path('product/<int:pk>/', staff_member_required(ticket_views.ProductDetailView.as_view()), name='product-detail'),
    path('product-type/new/', ticket_views.create_product_type, name='product-type-create'),
    path('product-type/list/', ticket_views.product_type_list, name='product-type-list'),
    path('product-type/<int:pk>/delete/', staff_member_required(ticket_views.ProductDeleteView.as_view()),name='product-type-delete'),
    path('product-type/<int:pk>/update/', ticket_views.update_product_type, name='product-type-update'),
    path('product-type/<int:pk>/', staff_member_required(ticket_views.ProductTypeDetailView.as_view()), name='product-type-detail'),
    path('status/new/', staff_member_required(ticket_views.StatusCreateView.as_view()), name='status-create'),
    path('status/list/', staff_member_required(ticket_views.StatusListView.as_view()), name='status-list'),
    path('status/<int:pk>/delete/', staff_member_required(ticket_views.StatusDeleteView.as_view()), name='status-delete'),
    path('status/<int:pk>/update/', ticket_views.StatusUpdateView.as_view(), name='status-update'),
    path('status/<int:pk>/', staff_member_required(ticket_views.StatusDetailView.as_view()), name='status-detail'),
    path('client/new/', ticket_views.create_client, name='client-create'),
    path('client/list/', ticket_views.client_list, name='client-list'),
    path('client/<int:pk>/', staff_member_required(ticket_views.ClientDetailView.as_view()), name='client-detail'),
    path('client/<int:pk>/update/', ticket_views.update_client, name='client-update'),
    path('client/<int:pk>/delete/', staff_member_required(ticket_views.ClientDeleteView.as_view()), name='client-delete'),
    path('hot-issue/new/', staff_member_required(ticket_views.HotIssueCreateView.as_view()), name='hot-issue-create'),
    path('hot-issue/list/', staff_member_required(ticket_views.HotIssueListView.as_view()), name='hot-issue-list'),
    path('hot-issue/<int:pk>/', staff_member_required(ticket_views.HotIssueDetailView.as_view()), name='hot-issue-detail'),
    path('hot-issue/<int:pk>/update/', ticket_views.HotIssueUpdateView.as_view(), name='hot-issue-update'),
    path('hot-issue/<int:pk>/delete/', staff_member_required(ticket_views.HotIssueDeleteView.as_view()), name='hot-issue-delete'),
    path('module/new/', ticket_views.create_module, name='module-create'),
    path('module/list/', ticket_views.module_list, name='module-list'),
    path('module/<int:pk>/', staff_member_required(ticket_views.ModuleDetailView.as_view()), name='module-detail'),
    path('module/<int:pk>/update/', ticket_views.update_module, name='module-update'),
    path('module/<int:pk>/delete/', staff_member_required(ticket_views.ModuleDeleteView.as_view()), name='module-delete'),
    path('about/', ticket_views.about, name='ticket-about'),
    path(r'ckeditor/', include('ckeditor_uploader.urls')),

]
