# Generated by Django 3.0.5 on 2020-05-12 14:56

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_code', models.CharField(blank=True, default='cat122256487302', max_length=20, verbose_name='Category Code')),
                ('cat_name', models.CharField(blank=True, default='', max_length=25, verbose_name='Name')),
                ('cat_description', models.CharField(blank=True, max_length=45, verbose_name='Description')),
                ('cat_last_update', models.DateTimeField(auto_now=True)),
                ('cat_date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_code', models.CharField(blank=True, default='client122256487302', max_length=20, verbose_name='Client Code')),
                ('client_name', models.CharField(blank=True, default='', max_length=50, verbose_name='Client name')),
                ('client_address', models.CharField(max_length=100, verbose_name='Address')),
                ('client_last_update', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('client_date_added', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('comment_date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotIssue',
            fields=[
                ('hi_id', models.AutoField(primary_key=True, serialize=False)),
                ('hi_code', models.CharField(blank=True, default='hi122256487302', max_length=20, verbose_name='Hot-issue Code')),
                ('hi_name', models.CharField(max_length=25, verbose_name='Name')),
                ('hi_description', models.CharField(max_length=45, verbose_name='Description')),
                ('hi_last_update', models.DateTimeField(auto_now=True)),
                ('hi_date_added', models.DateTimeField(auto_now_add=True)),
                ('hi_date_closed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('mod_id', models.AutoField(primary_key=True, serialize=False)),
                ('mod_code', models.CharField(blank=True, default='mod122256487302', max_length=20, verbose_name='Module Code')),
                ('mod_name', models.CharField(max_length=25, verbose_name='Name')),
                ('mod_description', models.CharField(max_length=45, verbose_name='Description')),
                ('mod_last_update', models.DateTimeField(auto_now=True)),
                ('mod_date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_code', models.CharField(blank=True, default='prod1252256487302', max_length=20, verbose_name='Product Code')),
                ('prod_name', models.CharField(blank=True, default='', max_length=25, verbose_name='Name')),
                ('prod_description', models.CharField(max_length=250, verbose_name='Description')),
                ('prod_last_update', models.DateTimeField(auto_now=True)),
                ('prod_date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('prod_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_type_code', models.CharField(blank=True, default='stat122256487302', max_length=20, verbose_name='Code')),
                ('prod_type_name', models.CharField(blank=True, default='', max_length=25, verbose_name='Name')),
                ('prod_type_description', models.CharField(max_length=250, verbose_name='Description')),
                ('prod_type_last_update', models.DateTimeField(auto_now=True)),
                ('prod_type_date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('proj_id', models.AutoField(primary_key=True, serialize=False)),
                ('proj_code', models.CharField(blank=True, default='proj122256487302', max_length=20, verbose_name='Project Code')),
                ('proj_name', models.CharField(blank=True, default='', max_length=25, verbose_name='Name')),
                ('proj_description', models.CharField(max_length=250, verbose_name='Description')),
                ('proj_complete_date', models.DateTimeField(blank=True, null=True)),
                ('proj_warranty_end', models.DateField(blank=True, null=True, verbose_name='Warranty Until')),
                ('proj_last_update', models.DateTimeField(blank=True, null=True)),
                ('proj_date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('stat_id', models.AutoField(primary_key=True, serialize=False)),
                ('stat_code', models.CharField(blank=True, default='stat122256487302', max_length=20, verbose_name='Code')),
                ('stat_name', models.CharField(blank=True, default='', max_length=25, verbose_name='Name')),
                ('stat_description', models.CharField(max_length=250, verbose_name='Description')),
                ('stat_last_update', models.DateTimeField(auto_now=True)),
                ('stat_date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('scat_id', models.AutoField(primary_key=True, serialize=False)),
                ('scat_code', models.CharField(blank=True, default='subcat122256487302', max_length=20, verbose_name='Subcategory Code')),
                ('scat_name', models.CharField(blank=True, default='', max_length=25, verbose_name='Name')),
                ('scat_description', models.CharField(max_length=45, verbose_name='Description')),
                ('scat_last_update', models.DateTimeField(auto_now=True)),
                ('scat_date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_code', models.CharField(blank=True, default='2020512487302', max_length=50, verbose_name='Ticket Code')),
                ('title', models.CharField(max_length=50)),
                ('description', ckeditor.fields.RichTextField()),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='YearlyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('attachment_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, upload_to='attachments')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_attachment_id', to='tickets.Ticket')),
            ],
        ),
    ]
