# Generated by Django 3.0.5 on 2020-05-14 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0005_auto_20200513_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotissue',
            name='hi_closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hi_closed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_code',
            field=models.CharField(blank=True, default='cat141156187427', max_length=20, verbose_name='Category Code'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_code',
            field=models.CharField(blank=True, default='client141156187427', max_length=20, verbose_name='Client Code'),
        ),
        migrations.AlterField(
            model_name='hotissue',
            name='hi_code',
            field=models.CharField(blank=True, default='hi141156187427', max_length=20, verbose_name='Hot-issue Code'),
        ),
        migrations.AlterField(
            model_name='module',
            name='mod_code',
            field=models.CharField(blank=True, default='mod141156187427', max_length=20, verbose_name='Module Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_code',
            field=models.CharField(blank=True, default='prod1451156187427', max_length=20, verbose_name='Product Code'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='prod_type_code',
            field=models.CharField(blank=True, default='stat141156187427', max_length=20, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='project',
            name='proj_code',
            field=models.CharField(blank=True, default='proj141156187427', max_length=20, verbose_name='Project Code'),
        ),
        migrations.AlterField(
            model_name='status',
            name='stat_code',
            field=models.CharField(blank=True, default='stat141156187427', max_length=20, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='scat_code',
            field=models.CharField(blank=True, default='subcat141156187427', max_length=20, verbose_name='Subcategory Code'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_code',
            field=models.CharField(blank=True, default='2020514187427', max_length=50, verbose_name='Ticket Code'),
        ),
    ]
