# Generated by Django 3.0.5 on 2020-06-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20200514_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_code',
            field=models.CharField(blank=True, default='cat241416518321', max_length=20, verbose_name='Category Code'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_code',
            field=models.CharField(blank=True, default='client241416518321', max_length=20, verbose_name='Client Code'),
        ),
        migrations.AlterField(
            model_name='hotissue',
            name='hi_code',
            field=models.CharField(blank=True, default='hi241416518321', max_length=20, verbose_name='Hot-issue Code'),
        ),
        migrations.AlterField(
            model_name='module',
            name='mod_code',
            field=models.CharField(blank=True, default='mod241416518321', max_length=20, verbose_name='Module Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_code',
            field=models.CharField(blank=True, default='prod2461416518321', max_length=20, verbose_name='Product Code'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='prod_type_code',
            field=models.CharField(blank=True, default='stat241416518321', max_length=20, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='project',
            name='proj_code',
            field=models.CharField(blank=True, default='proj241416518321', max_length=20, verbose_name='Project Code'),
        ),
        migrations.AlterField(
            model_name='status',
            name='stat_code',
            field=models.CharField(blank=True, default='stat241416518321', max_length=20, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='scat_code',
            field=models.CharField(blank=True, default='subcat241416518321', max_length=20, verbose_name='Subcategory Code'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_code',
            field=models.CharField(blank=True, default='2020624518321', max_length=50, verbose_name='Ticket Code'),
        ),
    ]
